[package]
name = "bastion"
version = "0.1.0"
type = "lib"
description = ""
author = ""

[archive.task.bastion.new]
command = "bastion.new"
module  = "lib/forge/new.march"

[archive.task.bastion.server]
command = "bastion.server"
module  = "lib/forge/server.march"

[archive.task.bastion.routes]
command = "bastion.routes"
module  = "lib/forge/routes.march"

[archive.task.bastion.assets]
command = "bastion.assets"
module  = "lib/forge/assets.march"

[archive.task.bastion.gen.auth]
command = "bastion.gen.auth"
module  = "lib/forge/gen_auth.march"

[archive.task.bastion.gen.schema]
command = "bastion.gen.schema"
module  = "lib/forge/gen_schema.march"

[archive.task.bastion.gen.island]
command = "bastion.gen.island"
module  = "lib/forge/gen_island.march"

[archive.task.bastion.build.islands]
command = "bastion.build.islands"
module  = "lib/forge/build_islands.march"

[archive.task.bastion.gen.handler]
command = "bastion.gen.handler"
module  = "lib/forge/gen_handler.march"

[archive.task.bastion.gen.context]
command = "bastion.gen.context"
module  = "lib/forge/gen_context.march"

[archive.task.bastion.gen.channel]
command = "bastion.gen.channel"
module  = "lib/forge/gen_channel.march"

[archive.task.bastion.gen.migration]
command = "bastion.gen.migration"
module  = "lib/forge/gen_migration.march"

[archive.task.bastion.lower]
command = "bastion.lower"
module  = "lib/forge/lower.march"

[archive.task.bastion.depot.migrate]
command = "bastion.depot.migrate"
module  = "lib/forge/depot_migrate.march"

[archive.task.bastion.depot.rollback]
command = "bastion.depot.rollback"
module  = "lib/forge/depot_rollback.march"

[archive.task.bastion.depot.migrations]
command = "bastion.depot.migrations"
module  = "lib/forge/depot_migrations.march"

[archive.task.bastion.depot.reset]
command = "bastion.depot.reset"
module  = "lib/forge/depot_reset.march"

[archive.task.bastion.release]
command = "bastion.release"
module  = "lib/forge/release.march"

[preprocessors]
".march.html" = "bastion lower"

[deps]
depot = { path = "/Users/80197052/code/depot" }
