[package]
name = "bastion"
version = "0.1.0"
type = "lib"
description = ""
author = ""

[archive.task.bastion.gen.island]
command = "bastion.gen.island"
module  = "lib/forge/gen_island.march"

[archive.task.bastion.build.islands]
command = "bastion.build.islands"
module  = "lib/forge/build_islands.march"

[deps]
