/**
 * WASM Bridge for Bastion Islands — Phase 4
 *
 * Loads compiled March island WASM modules and provides a JS interface
 * for calling the exported island functions (init, update, render).
 *
 * WASM memory layout for March strings (wasm32):
 *   offset  0 : i64  rc        (reference count, ignored by JS)
 *   offset  8 : i32  tag       (type tag)
 *   offset 12 : i32  pad
 *   offset 16 : i64  length    (byte count)
 *   offset 24 : i32  data_ptr  (pointer to char data in WASM linear memory)
 *
 * Island WASM exports (generated by the March compiler for Wasm32Unknown):
 *   march_island_init()                           → ptr  (initial State)
 *   march_island_render(ptr state)                → ptr  (IOList)
 *   march_island_render_html(ptr state)           → ptr  (String — flat HTML)
 *   march_island_update(ptr state, ptr msg)       → ptr  (new State)
 *   march_island_msg_from_name(ptr data, i32 len) → ptr  (Msg | null)
 *   march_island_string_length(ptr str)           → i32
 *   march_island_string_data(ptr str)             → ptr
 *   march_alloc_export(i64 size)                  → ptr
 *   march_string_lit_export(ptr s, i64 len)       → ptr
 *   march_dealloc(ptr p)                          → void
 */
(() => {
  'use strict';

  /**
   * A loaded WASM island module with state management and render/update.
   */
  class WasmIslandModule {
    /**
     * @param {WebAssembly.Instance} instance
     * @param {string} moduleName
     */
    constructor(instance, moduleName) {
      this.instance = instance;
      this.exports = instance.exports;
      this.moduleName = moduleName;
      /** @type {number|null} Opaque WASM heap pointer for current state */
      this.statePtr = null;
      /** @type {WebAssembly.Memory} */
      this.memory = instance.exports.memory;
    }

    /**
     * Initialize state by calling march_island_init().
     * Falls back gracefully if init is not exported.
     */
    initState() {
      if (typeof this.exports.march_island_init === 'function') {
        try {
          this.statePtr = this.exports.march_island_init();
        } catch (e) {
          console.warn(`[bastion/wasm] ${this.moduleName}.init() failed:`, e);
          this.statePtr = null;
        }
      }
    }

    /**
     * Read a March String from WASM memory at the given pointer.
     * Returns a JS string, or null if ptr is 0/falsy.
     * @param {number} ptr
     * @returns {string|null}
     */
    _readString(ptr) {
      if (!ptr) return null;
      const mem = new DataView(this.memory.buffer);
      // length is i64 at offset 16; clamp to 32-bit for JS safety
      const lenLo = mem.getUint32(ptr + 16, true);
      // data ptr is i32 (wasm32) at offset 24
      const dataPtr = mem.getUint32(ptr + 24, true);
      if (!dataPtr || lenLo === 0) return '';
      const bytes = new Uint8Array(this.memory.buffer, dataPtr, lenLo);
      return new TextDecoder('utf-8').decode(bytes);
    }

    /**
     * Write a JS string into WASM memory and return a March String ptr.
     * Uses march_alloc_export + march_string_lit_export.
     * @param {string} jsStr
     * @returns {number} WASM ptr to March String
     */
    _writeString(jsStr) {
      const encoded = new TextEncoder().encode(jsStr);
      const len = encoded.length;
      // Allocate raw bytes in WASM heap
      const rawPtr = this.exports.march_alloc_export(BigInt(len + 1));
      if (!rawPtr) return 0;
      const heap = new Uint8Array(this.memory.buffer);
      heap.set(encoded, rawPtr);
      heap[rawPtr + len] = 0; // null-terminate
      // Wrap in a March String object
      return this.exports.march_string_lit_export(rawPtr, BigInt(len));
    }

    /**
     * Render the current state to an HTML string.
     * Uses march_island_render_html which returns a flat String ptr.
     * @returns {string|null}
     */
    render() {
      if (!this.statePtr) return null;
      if (typeof this.exports.march_island_render_html !== 'function') return null;
      try {
        const strPtr = this.exports.march_island_render_html(this.statePtr);
        return this._readString(strPtr);
      } catch (e) {
        console.warn(`[bastion/wasm] ${this.moduleName}.render() failed:`, e);
        return null;
      }
    }

    /**
     * Apply a message to the state.
     *
     * msgPayload is either:
     *   - A plain string like "Increment" — a zero-field enum variant name.
     *   - An object like { tag: "Increment" } — zero-field enum (no extra fields).
     *   - An object like { tag: "SetValue", value: 3 } — enum with payload.
     *
     * For zero-field enum messages, uses march_island_msg_from_name() to
     * construct the typed Msg value directly without JSON serialization.
     * For payloaded messages, falls back to JSON string serialization.
     *
     * Returns true if the state was updated, false otherwise.
     * @param {string|Object} msgPayload
     * @returns {boolean}
     */
    update(msgPayload) {
      if (!this.statePtr) return false;
      if (typeof this.exports.march_island_update !== 'function') return false;

      // ── Fast path: zero-field enum via march_island_msg_from_name ────────────
      //
      // A zero-field enum message is one that only has a "tag" key and no other
      // payload fields (e.g. { tag: "Increment" } or the bare string "Increment").
      // The compiler exports march_island_msg_from_name(ptr, len) → Msg ptr for
      // these variants; it avoids JSON parsing on the WASM side.
      const msgPtr = this._buildMsgPtr(msgPayload);
      if (msgPtr === null) return false;

      try {
        const newStatePtr = this.exports.march_island_update(this.statePtr, msgPtr);
        if (newStatePtr) {
          this.statePtr = newStatePtr;
          return true;
        }
      } catch (e) {
        console.warn(`[bastion/wasm] ${this.moduleName}.update() failed:`, e);
      }
      return false;
    }

    /**
     * Build a WASM Msg pointer from msgPayload.
     *
     * Zero-field enum fast path (march_island_msg_from_name):
     *   - Plain string payload: use the string directly as the variant name.
     *   - Object with only a "tag" key: use tag as the variant name.
     *
     * JSON fallback (for payloaded messages):
     *   - Object with fields beyond "tag": serialize to JSON string.
     *
     * Returns the WASM Msg ptr, or null on error.
     * @param {string|Object} msgPayload
     * @returns {number|null}
     */
    _buildMsgPtr(msgPayload) {
      // Determine if this is a zero-field enum
      let variantName = null;

      if (typeof msgPayload === 'string') {
        // Plain string — always a zero-field variant name
        variantName = msgPayload;
      } else if (msgPayload && typeof msgPayload === 'object') {
        const keys = Object.keys(msgPayload);
        if (keys.length === 1 && keys[0] === 'tag') {
          // Object with only a "tag" key — zero-field enum
          variantName = msgPayload.tag;
        }
      }

      // Zero-field enum: use march_island_msg_from_name if exported
      if (variantName !== null && typeof this.exports.march_island_msg_from_name === 'function') {
        try {
          const encoded = new TextEncoder().encode(variantName);
          const len = encoded.length;
          const rawPtr = this.exports.march_alloc_export(BigInt(len + 1));
          if (!rawPtr) return null;
          const heap = new Uint8Array(this.memory.buffer);
          heap.set(encoded, rawPtr);
          heap[rawPtr + len] = 0;
          const msgPtr = this.exports.march_island_msg_from_name(rawPtr, len);
          if (msgPtr) return msgPtr;
          // march_island_msg_from_name returned null — variant name not found.
          // Fall through to JSON path so the WASM side can report the error.
        } catch (e) {
          console.warn(`[bastion/wasm] march_island_msg_from_name failed for "${variantName}":`, e);
        }
      }

      // JSON fallback: serialize the payload and pass as a March String
      let msgStr;
      if (typeof msgPayload === 'string') {
        // Plain string but no march_island_msg_from_name — wrap in JSON tag object
        msgStr = JSON.stringify({ tag: msgPayload });
      } else {
        msgStr = JSON.stringify(msgPayload);
      }

      try {
        const ptr = this._writeString(msgStr);
        return ptr || null;
      } catch (e) {
        console.warn(`[bastion/wasm] failed to write msg string for "${msgStr}":`, e);
        return null;
      }
    }

    /**
     * Apply a message to the state, returning both the success flag AND
     * any Cmd produced by the island's update function.
     *
     * Requires the WASM module to export:
     *   march_island_update_cmd(state_ptr, msg_ptr)  → new_state_ptr
     *   march_island_last_cmd()                       → cmd_json_str_ptr | 0
     *
     * The compiler emits march_island_update_cmd instead of march_island_update
     * when the island's update function returns (State, Cmd(Msg)) tuples.
     * march_island_last_cmd() returns the Cmd portion of the last call's result.
     *
     * Falls back to the plain update() path if march_island_update_cmd is absent.
     *
     * @param {string|Object} msgPayload
     * @returns {{ updated: boolean, cmd: Object|null }}
     */
    updateWithCmd(msgPayload) {
      // Fast path: island doesn't produce Cmds
      if (typeof this.exports.march_island_update_cmd !== 'function') {
        const updated = this.update(msgPayload);
        return { updated, cmd: null };
      }
      if (!this.statePtr) return { updated: false, cmd: null };

      const msgPtr = this._buildMsgPtr(msgPayload);
      if (msgPtr === null) return { updated: false, cmd: null };

      try {
        const newStatePtr = this.exports.march_island_update_cmd(this.statePtr, msgPtr);
        if (!newStatePtr) return { updated: false, cmd: null };

        this.statePtr = newStatePtr;

        // Read the Cmd if march_island_last_cmd is exported
        let cmd = null;
        if (typeof this.exports.march_island_last_cmd === 'function') {
          const cmdPtr = this.exports.march_island_last_cmd();
          if (cmdPtr) {
            const cmdStr = this._readString(cmdPtr);
            if (cmdStr) {
              try { cmd = JSON.parse(cmdStr); } catch (_) {}
            }
          }
        }
        return { updated: true, cmd };
      } catch (e) {
        console.warn(`[bastion/wasm] ${this.moduleName}.update_with_cmd() failed:`, e);
        return { updated: false, cmd: null };
      }
    }

    /**
     * Merge remote state into local state.
     * Phase 5: default is server-wins (discard local, use server HTML).
     * Custom merge functions are not yet wired through the WASM boundary.
     * @param {Object} _remoteState
     */
    merge(_remoteState) {
      // Phase 5: server HTML arrives via 'render' message and morphs the DOM.
      // Local statePtr is not updated here — server's rendered HTML is authoritative.
    }
  }

  /**
   * Manages loading and caching of WASM island modules.
   */
  class WasmBridge {
    constructor() {
      /** @type {Map<string, WasmIslandModule>} */
      this.modules = new Map();
      /** @type {Map<string, Promise<WasmIslandModule|null>>} */
      this._loading = new Map();
      /** @type {string} URL prefix for island WASM files */
      this.islandsBasePath = '/_bastion/islands';
      /** @type {boolean} True until at least one WASM module is loaded */
      this.serverRendering = true;
    }

    /**
     * Load a WASM module for the given island module name.
     * Caches the result; concurrent calls for the same name share the promise.
     * @param {string} moduleName
     * @returns {Promise<WasmIslandModule|null>}
     */
    async loadModule(moduleName) {
      if (this.modules.has(moduleName)) {
        return this.modules.get(moduleName);
      }
      if (this._loading.has(moduleName)) {
        return this._loading.get(moduleName);
      }

      const promise = this._fetchAndInstantiate(moduleName);
      this._loading.set(moduleName, promise);

      const mod = await promise;
      this._loading.delete(moduleName);
      if (mod) {
        this.modules.set(moduleName, mod);
        this.serverRendering = false;
      }
      return mod;
    }

    /**
     * @param {string} moduleName
     * @returns {Promise<WasmIslandModule|null>}
     */
    async _fetchAndInstantiate(moduleName) {
      const url = `${this.islandsBasePath}/${moduleName}.wasm`;
      try {
        // ── JS FFI handle table ───────────────────────────────────────────────
        // JS objects are stored in a handle table keyed by integer handles.
        // WASM code passes handles back to JS for further DOM/API operations.
        const jsHandles = new Map();
        let jsHandleCounter = 1;
        const js_store = (val) => {
          if (val === null || val === undefined) return 0;
          const h = jsHandleCounter++;
          jsHandles.set(h, val);
          return h;
        };
        const js_load = (h) => h ? jsHandles.get(h) : undefined;

        // Late-bound memory reference.  importObject closures capture this ref;
        // it is patched to the actual WASM memory after instantiation.
        let wasmMemory = null;
        const readStr = (ptr) => {
          if (!ptr || !wasmMemory) return '';
          const mem = new DataView(wasmMemory.buffer);
          const lenLo  = mem.getUint32(ptr + 16, true);
          const dataPtr = mem.getUint32(ptr + 24, true);
          if (!dataPtr || lenLo === 0) return '';
          const bytes = new Uint8Array(wasmMemory.buffer, dataPtr, lenLo);
          return new TextDecoder('utf-8').decode(bytes);
        };
        const resolvePath = (path, root) => {
          if (!path) return undefined;
          return path.split('.').reduce((obj, key) => obj != null ? obj[key] : undefined, root);
        };

        // WASM imports: declare external functions used by March runtime stubs
        // and the Bastion.JS FFI (lib/js.march).
        const importObject = {
          env: {
            march_print:    () => {},
            march_println:  () => {},
            march_panic:    () => { throw new Error('march panic'); },
          },
          // Bastion.JS FFI — matches `extern "bastion" "js_*"` declarations in lib/js.march
          bastion: {
            js_call: (funcPathPtr, _argsPtr) => {
              const funcPath = readStr(funcPathPtr);
              const fn_ = resolvePath(funcPath, window);
              if (typeof fn_ !== 'function') return 0;
              // args: March list traversal deferred — call with no args for now
              try { return js_store(fn_()); } catch (_) { return 0; }
            },
            js_global: (propPathPtr) => {
              const val = resolvePath(readStr(propPathPtr), window);
              return js_store(val !== undefined ? val : null);
            },
            js_eval: (codePtr) => {
              try { return js_store(eval(readStr(codePtr))); } catch (_) { return 0; } // eslint-disable-line no-eval
            },
            js_query_selector: (selectorPtr) => {
              try { return js_store(document.querySelector(readStr(selectorPtr))); } catch (_) { return 0; }
            },
            js_get_attribute: (h, attrPtr) => {
              const el = js_load(h);
              if (!el || typeof el.getAttribute !== 'function') return 0;
              const v = el.getAttribute(readStr(attrPtr));
              return js_store(v !== null ? v : null);
            },
            js_set_attribute: (h, attrPtr, valuePtr) => {
              const el = js_load(h);
              if (el && typeof el.setAttribute === 'function')
                el.setAttribute(readStr(attrPtr), readStr(valuePtr));
              return 0;
            },
            js_remove_attribute: (h, attrPtr) => {
              const el = js_load(h);
              if (el && typeof el.removeAttribute === 'function')
                el.removeAttribute(readStr(attrPtr));
              return 0;
            },
            // Full callback support requires WASM function table — deferred
            js_add_event_listener: (_h, _eventPtr, _handlerPtr) => 0,
            js_string_to_ref: (strPtr)  => js_store(readStr(strPtr)),
            js_int_to_ref:    (n)       => js_store(n),
            js_bool_to_ref:   (b)       => js_store(!!b),
            js_json_to_ref:   (strPtr)  => {
              try { return js_store(JSON.parse(readStr(strPtr))); } catch (_) { return 0; }
            },
            // js_ref_to_string: writing a March String back into WASM memory requires
            // march_alloc_export — deferred until island compiler support is complete
            js_ref_to_string: (_h, _outPtr) => 0,
            js_ref_to_int: (h) => {
              const v = js_load(h);
              return typeof v === 'number' ? v : 0;
            },
          },
        };

        let instance;
        if (typeof WebAssembly.instantiateStreaming === 'function') {
          const resp = await fetch(url);
          if (!resp.ok) {
            // WASM not available yet (not compiled) — silently fall back
            return null;
          }
          const result = await WebAssembly.instantiateStreaming(resp, importObject);
          instance = result.instance;
        } else {
          // Fallback for environments without instantiateStreaming
          const resp = await fetch(url);
          if (!resp.ok) return null;
          const bytes = await resp.arrayBuffer();
          const result = await WebAssembly.instantiate(bytes, importObject);
          instance = result.instance;
        }

        // Patch the late-bound memory reference so FFI imports can read strings
        wasmMemory = instance.exports.memory;

        const mod = new WasmIslandModule(instance, moduleName);
        mod.initState();
        console.log(`[bastion/wasm] loaded ${moduleName}.wasm`);
        return mod;
      } catch (e) {
        // Network error, WASM compile error, or file not found — not fatal
        if (e.name !== 'TypeError' && !(e instanceof TypeError)) {
          console.warn(`[bastion/wasm] failed to load ${moduleName}.wasm:`, e);
        }
        return null;
      }
    }

    /**
     * Get a previously loaded module synchronously, or null if not loaded.
     * @param {string} moduleName
     * @returns {WasmIslandModule|null}
     */
    getModule(moduleName) {
      return this.modules.get(moduleName) || null;
    }

    /**
     * Check whether all rendering still goes through the server.
     * @returns {boolean}
     */
    isServerRendering() {
      return this.serverRendering;
    }
  }

  window.__bastionWasm = new WasmBridge();
})();
