/**
 * WASM Bridge for Bastion Islands — Phase 4
 *
 * Loads compiled March island WASM modules and provides a JS interface
 * for calling the exported island functions (init, update, render).
 *
 * WASM memory layout for March strings (wasm32):
 *   offset  0 : i64  rc        (reference count, ignored by JS)
 *   offset  8 : i32  tag       (type tag)
 *   offset 12 : i32  pad
 *   offset 16 : i64  length    (byte count)
 *   offset 24 : i32  data_ptr  (pointer to char data in WASM linear memory)
 *
 * Island WASM exports (generated by the March compiler for Wasm32Unknown):
 *   march_island_init()                           → ptr  (initial State)
 *   march_island_render(ptr state)                → ptr  (IOList)
 *   march_island_render_html(ptr state)           → ptr  (String — flat HTML)
 *   march_island_update(ptr state, ptr msg)       → ptr  (new State)
 *   march_island_msg_from_name(ptr data, i32 len) → ptr  (Msg | null)
 *   march_island_string_length(ptr str)           → i32
 *   march_island_string_data(ptr str)             → ptr
 *   march_alloc_export(i64 size)                  → ptr
 *   march_string_lit_export(ptr s, i64 len)       → ptr
 *   march_dealloc(ptr p)                          → void
 */
(() => {
  'use strict';

  /**
   * A loaded WASM island module with state management and render/update.
   */
  class WasmIslandModule {
    /**
     * @param {WebAssembly.Instance} instance
     * @param {string} moduleName
     */
    constructor(instance, moduleName) {
      this.instance = instance;
      this.exports = instance.exports;
      this.moduleName = moduleName;
      /** @type {number|null} Opaque WASM heap pointer for current state */
      this.statePtr = null;
      /** @type {WebAssembly.Memory} */
      this.memory = instance.exports.memory;
    }

    /**
     * Initialize state by calling march_island_init().
     * Falls back gracefully if init is not exported.
     */
    initState() {
      if (typeof this.exports.march_island_init === 'function') {
        try {
          this.statePtr = this.exports.march_island_init();
        } catch (e) {
          console.warn(`[bastion/wasm] ${this.moduleName}.init() failed:`, e);
          this.statePtr = null;
        }
      }
    }

    /**
     * Read a March String from WASM memory at the given pointer.
     * Returns a JS string, or null if ptr is 0/falsy.
     * @param {number} ptr
     * @returns {string|null}
     */
    _readString(ptr) {
      if (!ptr) return null;
      const mem = new DataView(this.memory.buffer);
      // length is i64 at offset 16; clamp to 32-bit for JS safety
      const lenLo = mem.getUint32(ptr + 16, true);
      // data ptr is i32 (wasm32) at offset 24
      const dataPtr = mem.getUint32(ptr + 24, true);
      if (!dataPtr || lenLo === 0) return '';
      const bytes = new Uint8Array(this.memory.buffer, dataPtr, lenLo);
      return new TextDecoder('utf-8').decode(bytes);
    }

    /**
     * Write a JS string into WASM memory and return a March String ptr.
     * Uses march_alloc_export + march_string_lit_export.
     * @param {string} jsStr
     * @returns {number} WASM ptr to March String
     */
    _writeString(jsStr) {
      const encoded = new TextEncoder().encode(jsStr);
      const len = encoded.length;
      // Allocate raw bytes in WASM heap
      const rawPtr = this.exports.march_alloc_export(BigInt(len + 1));
      if (!rawPtr) return 0;
      const heap = new Uint8Array(this.memory.buffer);
      heap.set(encoded, rawPtr);
      heap[rawPtr + len] = 0; // null-terminate
      // Wrap in a March String object
      return this.exports.march_string_lit_export(rawPtr, BigInt(len));
    }

    /**
     * Render the current state to an HTML string.
     * Uses march_island_render_html which returns a flat String ptr.
     * @returns {string|null}
     */
    render() {
      if (!this.statePtr) return null;
      if (typeof this.exports.march_island_render_html !== 'function') return null;
      try {
        const strPtr = this.exports.march_island_render_html(this.statePtr);
        return this._readString(strPtr);
      } catch (e) {
        console.warn(`[bastion/wasm] ${this.moduleName}.render() failed:`, e);
        return null;
      }
    }

    /**
     * Apply a message to the state.
     * msgPayload is a string (variant name like "Increment") or a JSON object.
     * Returns true if the state was updated.
     * @param {string|Object} msgPayload
     * @returns {boolean}
     */
    update(msgPayload) {
      if (!this.statePtr) return false;
      if (typeof this.exports.march_island_update !== 'function') return false;

      let msgStr;
      if (typeof msgPayload === 'string') {
        msgStr = msgPayload;
      } else {
        // For structured payloads use the "tag" field if present, else JSON
        msgStr = (msgPayload && msgPayload.type) ? msgPayload.type : JSON.stringify(msgPayload);
      }

      let msgPtr = 0;
      // Try march_island_msg_from_name for enum-style messages
      if (typeof this.exports.march_island_msg_from_name === 'function') {
        try {
          const encoded = new TextEncoder().encode(msgStr);
          const rawPtr = this.exports.march_alloc_export(BigInt(encoded.length + 1));
          if (rawPtr) {
            const heap = new Uint8Array(this.memory.buffer);
            heap.set(encoded, rawPtr);
            heap[rawPtr + encoded.length] = 0;
            msgPtr = this.exports.march_island_msg_from_name(rawPtr, encoded.length);
          }
        } catch (e) {
          console.warn(`[bastion/wasm] msg_from_name failed for "${msgStr}":`, e);
        }
      }

      if (!msgPtr) return false;  // unknown message — server handles it

      try {
        const newStatePtr = this.exports.march_island_update(this.statePtr, msgPtr);
        if (newStatePtr) {
          this.statePtr = newStatePtr;
          return true;
        }
      } catch (e) {
        console.warn(`[bastion/wasm] ${this.moduleName}.update() failed:`, e);
      }
      return false;
    }

    /**
     * Merge remote state into local state.
     * Phase 5: default is server-wins (discard local, use server HTML).
     * Custom merge functions are not yet wired through the WASM boundary.
     * @param {Object} _remoteState
     */
    merge(_remoteState) {
      // Phase 5: server HTML arrives via 'render' message and morphs the DOM.
      // Local statePtr is not updated here — server's rendered HTML is authoritative.
    }
  }

  /**
   * Manages loading and caching of WASM island modules.
   */
  class WasmBridge {
    constructor() {
      /** @type {Map<string, WasmIslandModule>} */
      this.modules = new Map();
      /** @type {Map<string, Promise<WasmIslandModule|null>>} */
      this._loading = new Map();
      /** @type {string} URL prefix for island WASM files */
      this.islandsBasePath = '/_bastion/islands';
      /** @type {boolean} True until at least one WASM module is loaded */
      this.serverRendering = true;
    }

    /**
     * Load a WASM module for the given island module name.
     * Caches the result; concurrent calls for the same name share the promise.
     * @param {string} moduleName
     * @returns {Promise<WasmIslandModule|null>}
     */
    async loadModule(moduleName) {
      if (this.modules.has(moduleName)) {
        return this.modules.get(moduleName);
      }
      if (this._loading.has(moduleName)) {
        return this._loading.get(moduleName);
      }

      const promise = this._fetchAndInstantiate(moduleName);
      this._loading.set(moduleName, promise);

      const mod = await promise;
      this._loading.delete(moduleName);
      if (mod) {
        this.modules.set(moduleName, mod);
        this.serverRendering = false;
      }
      return mod;
    }

    /**
     * @param {string} moduleName
     * @returns {Promise<WasmIslandModule|null>}
     */
    async _fetchAndInstantiate(moduleName) {
      const url = `${this.islandsBasePath}/${moduleName}.wasm`;
      try {
        // WASM imports: declare external functions used by March runtime stubs
        const importObject = {
          env: {
            march_print:    () => {},
            march_println:  () => {},
            march_panic:    () => { throw new Error('march panic'); },
          }
        };

        let instance;
        if (typeof WebAssembly.instantiateStreaming === 'function') {
          const resp = await fetch(url);
          if (!resp.ok) {
            // WASM not available yet (not compiled) — silently fall back
            return null;
          }
          const result = await WebAssembly.instantiateStreaming(resp, importObject);
          instance = result.instance;
        } else {
          // Fallback for environments without instantiateStreaming
          const resp = await fetch(url);
          if (!resp.ok) return null;
          const bytes = await resp.arrayBuffer();
          const result = await WebAssembly.instantiate(bytes, importObject);
          instance = result.instance;
        }

        const mod = new WasmIslandModule(instance, moduleName);
        mod.initState();
        console.log(`[bastion/wasm] loaded ${moduleName}.wasm`);
        return mod;
      } catch (e) {
        // Network error, WASM compile error, or file not found — not fatal
        if (e.name !== 'TypeError' && !(e instanceof TypeError)) {
          console.warn(`[bastion/wasm] failed to load ${moduleName}.wasm:`, e);
        }
        return null;
      }
    }

    /**
     * Get a previously loaded module synchronously, or null if not loaded.
     * @param {string} moduleName
     * @returns {WasmIslandModule|null}
     */
    getModule(moduleName) {
      return this.modules.get(moduleName) || null;
    }

    /**
     * Check whether all rendering still goes through the server.
     * @returns {boolean}
     */
    isServerRendering() {
      return this.serverRendering;
    }
  }

  window.__bastionWasm = new WasmBridge();
})();
